/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cellbank;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author rayo
 */
public class bloqueo extends javax.swing.JFrame {

    /**
     * Creates new form bloqueo
     */
    public bloqueo() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(1,1, 363,654);
        setLocationRelativeTo(null);
    }

    public bloqueo(String tiempo) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(1,1, 363,654);
        setLocationRelativeTo(null);
        lbl_time.setText(tiempo);
    }
    public void setTime(String tiempo){
         lbl_time.setText(tiempo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_time.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(0, 102, 255));
        lbl_time.setText("00:00:00");
        lbl_time.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lbl_time);
        lbl_time.setBounds(100, 440, 170, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellbank/fondos/BLOQUEO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 594);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lbl_time;
    // End of variables declaration//GEN-END:variables
}
